version: "3.9"
services:
  course_pg_17:
    image: postgres
    restart: always
    container_name: course_pg_17
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    build:
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_URL: jdbc:postgresql://course_pg_17:5432/postgres
    depends_on:
      - course_pg_17