spring:
  application:
    name: course
  datasource:
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/course
server:
  port: 8080